using System.Text.Json;
using AwesomeAssertions;
using Pagefind.Net;
using TUnit;

namespace Pagefind.Net.Tests;

/// <summary>
/// HTML-level parity tests: uses <see cref="PagefindIndex.AddHtmlRecord"/> with
/// sections derived from the corpus HTML files, then compares the index output
/// against <c>Fixtures/reference-html-decoded/</c> (generated by pagefind's
/// <c>addHTMLFile</c> against the same HTML).
///
/// These tests verify that AddHtmlRecord's weight scheme, content joining,
/// anchor handling, and compound splitting match the official Pagefind binary.
/// </summary>
public sealed class HtmlParityTests
{
	private static readonly string ReferenceHtmlDir =
		Path.Combine(AppContext.BaseDirectory, "Fixtures", "reference-html-decoded");

	[Test]
	public async Task HtmlWordListMatchesOfficialBinary()
	{
		var refWordsPath = Path.Combine(ReferenceHtmlDir, "index-words.json");
		if (!File.Exists(refWordsPath))
			return;

		var (pagefindDir, cleanup) = await BuildAndWriteHtmlIndex();
		try
		{
			var ourIndex = IndexDecoder.ReadAllIndexChunks(Path.Combine(pagefindDir, "index"));
			var refJson = await File.ReadAllTextAsync(refWordsPath);
			using var refDoc = JsonDocument.Parse(refJson);

			var refWords = refDoc.RootElement.EnumerateObject()
				.Select(p => p.Name)
				.Order()
				.ToList();

			var ourWords = ourIndex.Keys.Order().ToList();

			ourWords.Should().BeEquivalentTo(refWords,
				"AddHtmlRecord should produce the same stemmed word list as addHTMLFile");
		}
		finally { cleanup(); }
	}

	[Test]
	public async Task HtmlPostingsMatchOfficialBinary()
	{
		var refWordsPath = Path.Combine(ReferenceHtmlDir, "index-words.json");
		if (!File.Exists(refWordsPath))
			return;

		var (pagefindDir, cleanup) = await BuildAndWriteHtmlIndex();
		try
		{
			var ourIndex = IndexDecoder.ReadAllIndexChunks(Path.Combine(pagefindDir, "index"));
			var refJson = await File.ReadAllTextAsync(refWordsPath);
			using var refDoc = JsonDocument.Parse(refJson);

			foreach (var refWord in refDoc.RootElement.EnumerateObject())
			{
				var word = refWord.Name;
				ourIndex.Should().ContainKey(word,
					$"word '{word}' exists in HTML reference but not in AddHtmlRecord output");

				var ourEntry = ourIndex[word];
				var refPostings = refWord.Value.GetProperty("postings");

				ourEntry.Postings.Should().HaveCount(refPostings.GetArrayLength(),
					$"word '{word}' should have the same number of page postings");

				var refPostingList = refPostings.EnumerateArray().ToList();
				for (var i = 0; i < ourEntry.Postings.Count; i++)
				{
					var ourPosting = ourEntry.Postings[i];
					var refPosting = refPostingList[i];

					ourPosting.PageIndex.Should().Be(refPosting.GetProperty("pageIndex").GetInt32(),
						$"word '{word}' posting[{i}] page index mismatch");

					var refLocs = refPosting.GetProperty("locs").EnumerateArray()
						.Select(e => e.GetInt32()).ToArray();
					ourPosting.Locs.Should().BeEquivalentTo(refLocs,
						$"word '{word}' posting[{i}] locs (weights + positions) mismatch");

					var refMetaLocs = refPosting.GetProperty("metaLocs").EnumerateArray()
						.Select(e => e.GetInt32()).ToArray();
					ourPosting.MetaLocs.Should().BeEquivalentTo(refMetaLocs,
						$"word '{word}' posting[{i}] metaLocs mismatch");
				}
			}
		}
		finally { cleanup(); }
	}

	[Test]
	public async Task HtmlFragmentContentMatchesOfficialBinary()
	{
		var refFragmentsPath = Path.Combine(ReferenceHtmlDir, "fragments.json");
		if (!File.Exists(refFragmentsPath))
			return;

		var (pagefindDir, cleanup) = await BuildAndWriteHtmlIndex();
		try
		{
			var ourFragments = IndexDecoder.ReadAllFragments(Path.Combine(pagefindDir, "fragment"));
			var refJson = await File.ReadAllTextAsync(refFragmentsPath);
			var refFragments = JsonSerializer.Deserialize<List<DecodedFragment>>(refJson,
				DecoderSerializerContext.Default.ListDecodedFragment)!;

			ourFragments.Should().HaveCount(refFragments.Count,
				"should produce the same number of fragments");

			for (var i = 0; i < ourFragments.Count; i++)
			{
				var ours = ourFragments[i];
				var theirs = refFragments[i];

				ours.Url.Should().Be(theirs.Url, $"fragment[{i}] URL mismatch");
				ours.Content.Should().Be(theirs.Content, $"fragment[{i}] content mismatch");
				ours.WordCount.Should().Be(theirs.WordCount, $"fragment[{i}] word count mismatch");
				ours.Meta.Should().BeEquivalentTo(theirs.Meta,
					$"fragment[{i}] ({ours.Url}) meta mismatch");

				ours.Anchors.Should().HaveCount(theirs.Anchors.Count,
					$"fragment[{i}] ({ours.Url}) anchor count mismatch");

				for (var a = 0; a < ours.Anchors.Count; a++)
				{
					ours.Anchors[a].Element.Should().Be(theirs.Anchors[a].Element,
						$"fragment[{i}] ({ours.Url}) anchor[{a}] element mismatch");
					ours.Anchors[a].Id.Should().Be(theirs.Anchors[a].Id,
						$"fragment[{i}] ({ours.Url}) anchor[{a}] id mismatch");
					ours.Anchors[a].Text.Should().Be(theirs.Anchors[a].Text,
						$"fragment[{i}] ({ours.Url}) anchor[{a}] text mismatch");
					ours.Anchors[a].Location.Should().Be(theirs.Anchors[a].Location,
						$"fragment[{i}] ({ours.Url}) anchor[{a}] location mismatch");
				}
			}
		}
		finally { cleanup(); }
	}

	[Test]
	public async Task HtmlMetaMatchesOfficialBinary()
	{
		var refMetaPath = Path.Combine(ReferenceHtmlDir, "meta.json");
		if (!File.Exists(refMetaPath))
			return;

		var (pagefindDir, cleanup) = await BuildAndWriteHtmlIndex();
		try
		{
			var ourMetaFile = IndexDecoder.FindMetaFile(pagefindDir);
			ourMetaFile.Should().NotBeNull("a .pf_meta file should exist");

			var ourMeta = IndexDecoder.ReadMeta(ourMetaFile!);
			var refJson = await File.ReadAllTextAsync(refMetaPath);
			var refMeta = JsonSerializer.Deserialize<DecodedMetaJson>(refJson)!;

			ourMeta.Version.Should().Be(refMeta.Version, "meta version mismatch");
			ourMeta.Pages.Should().HaveCount(refMeta.Pages.Count,
				"should have the same number of pages");

			for (var i = 0; i < ourMeta.Pages.Count; i++)
			{
				ourMeta.Pages[i].WordCount.Should().Be(refMeta.Pages[i].WordCount,
					$"page[{i}] word count mismatch");
			}
		}
		finally { cleanup(); }
	}

	// ── Helpers ────────────────────────────────────────────────────────────────

	private static async Task<(string PagefindDir, Action Cleanup)> BuildAndWriteHtmlIndex()
	{
		var outputDir = Path.Combine(Path.GetTempPath(), $"pagefind-net-html-parity-{Guid.NewGuid():N}");
		var index = BuildHtmlIndex();
		await index.WriteAsync(outputDir, CancellationToken.None);
		var pagefindDir = Path.Combine(outputDir, "pagefind");
		return (pagefindDir, () =>
		{
			if (Directory.Exists(outputDir))
				Directory.Delete(outputDir, recursive: true);
		});
	}

	/// <summary>
	/// Builds the index using AddHtmlRecord with sections matching the corpus HTML files.
	/// The sections mirror the structure of getting-started.html, configuration.html,
	/// and api-reference.html — heading tags, element IDs, and body text.
	/// </summary>
	private static PagefindIndex BuildHtmlIndex()
	{
		var index = new PagefindIndex(new PagefindIndexOptions { Language = "en" });

		// getting-started.html
		index.AddHtmlRecord(new HtmlPageData
		{
			Url = "/getting-started/",
			Sections =
			[
				new HtmlSection("h1", "Getting Started"),
				new HtmlSection("p", "Welcome to pagefind-net. Install the NuGet package and call WriteAsync."),
				new HtmlSection("h2", "Installation", "installation"),
				new HtmlSection("p", "Run: dotnet add package Pagefind.Net"),
				new HtmlSection("h2", "Quickstart", "quickstart"),
				new HtmlSection("p", "Create a PagefindIndex and add records."),
			],
			Meta = new Dictionary<string, string> { ["title"] = "Getting Started" },
		});

		// configuration.html
		index.AddHtmlRecord(new HtmlPageData
		{
			Url = "/configuration/",
			Sections =
			[
				new HtmlSection("h1", "Configuration"),
				new HtmlSection("p", "Configure PagefindIndexOptions: Language, IncludeCharacters, WeightedSegments."),
				new HtmlSection("h2", "Language", "language"),
				new HtmlSection("p", "Set Language to a BCP-47 language tag such as en."),
				new HtmlSection("h2", "IncludeCharacters", "include-characters"),
				new HtmlSection("p", "Additional characters to keep during tokenisation."),
			],
			Meta = new Dictionary<string, string> { ["title"] = "Configuration" },
		});

		// api-reference.html
		index.AddHtmlRecord(new HtmlPageData
		{
			Url = "/api-reference/",
			Sections =
			[
				new HtmlSection("h1", "API Reference"),
				new HtmlSection("p", "Full reference for PagefindIndex, PagefindRecord, WeightedSegment, PagefindAnchor."),
				new HtmlSection("h2", "PagefindIndex", "pagefindindex"),
				new HtmlSection("p", "Main entry point. Call AddRecord then WriteAsync."),
				new HtmlSection("h2", "PagefindRecord", "pagefindrecord"),
				new HtmlSection("p", "Represents a single indexable document with Url, Title, Content."),
			],
			Meta = new Dictionary<string, string> { ["title"] = "API Reference" },
		});

		return index;
	}
}
