using System.Text.Json;
using AwesomeAssertions;
using Pagefind.Net;
using TUnit;

namespace Pagefind.Net.Tests;

/// <summary>
/// Deep structural parity tests comparing the decoded index output of
/// pagefind-net against the official Pagefind binary.
///
/// These tests use pre-decoded reference data from
/// <c>Fixtures/reference-decoded/</c> (generated by <c>generate-fixtures.mjs</c>).
/// All comparisons are structural — hash-based filenames and chunk boundaries
/// may legitimately differ.
///
/// Tests gracefully skip when fixtures are not present.
/// </summary>
public sealed class IndexParityTests
{
	private static readonly string ReferenceDecodedDir =
		Path.Combine(AppContext.BaseDirectory, "Fixtures", "reference-decoded");

	private static readonly string ReferenceDir =
		Path.Combine(AppContext.BaseDirectory, "Fixtures", "reference-pagefind");

	// ── Word List Parity ───────────────────────────────────────────────────────

	[Test]
	public async Task IndexWordListMatchesOfficialBinary()
	{
		var refWordsPath = Path.Combine(ReferenceDecodedDir, "index-words.json");
		if (!File.Exists(refWordsPath))
			return;

		var (pagefindDir, cleanup) = await BuildAndWriteIndex();
		try
		{
			var ourIndex = IndexDecoder.ReadAllIndexChunks(Path.Combine(pagefindDir, "index"));
			var refJson = await File.ReadAllTextAsync(refWordsPath);
			using var refDoc = JsonDocument.Parse(refJson);

			var refWords = refDoc.RootElement.EnumerateObject()
				.Select(p => p.Name)
				.Order()
				.ToList();

			var ourWords = ourIndex.Keys.Order().ToList();

			ourWords.Should().BeEquivalentTo(refWords,
				"the .NET indexer should produce the same stemmed word list as the official binary");
		}
		finally { cleanup(); }
	}

	// ── Postings Parity ────────────────────────────────────────────────────────

	[Test]
	public async Task IndexPostingsMatchOfficialBinary()
	{
		var refWordsPath = Path.Combine(ReferenceDecodedDir, "index-words.json");
		if (!File.Exists(refWordsPath))
			return;

		var (pagefindDir, cleanup) = await BuildAndWriteIndex();
		try
		{
			var ourIndex = IndexDecoder.ReadAllIndexChunks(Path.Combine(pagefindDir, "index"));
			var refJson = await File.ReadAllTextAsync(refWordsPath);
			using var refDoc = JsonDocument.Parse(refJson);

			foreach (var refWord in refDoc.RootElement.EnumerateObject())
			{
				var word = refWord.Name;
				ourIndex.Should().ContainKey(word,
					$"word '{word}' exists in reference index but not in .NET index");

				var ourEntry = ourIndex[word];
				var refPostings = refWord.Value.GetProperty("postings");

				ourEntry.Postings.Should().HaveCount(refPostings.GetArrayLength(),
					$"word '{word}' should have the same number of page postings");

				var refPostingList = refPostings.EnumerateArray().ToList();
				for (var i = 0; i < ourEntry.Postings.Count; i++)
				{
					var ourPosting = ourEntry.Postings[i];
					var refPosting = refPostingList[i];

					ourPosting.PageIndex.Should().Be(refPosting.GetProperty("pageIndex").GetInt32(),
						$"word '{word}' posting[{i}] page index mismatch");

					var refLocs = refPosting.GetProperty("locs").EnumerateArray()
						.Select(e => e.GetInt32()).ToArray();
					ourPosting.Locs.Should().BeEquivalentTo(refLocs,
						$"word '{word}' posting[{i}] locs (weights + positions) mismatch");
				}
			}
		}
		finally { cleanup(); }
	}

	// ── Fragment Content Parity ────────────────────────────────────────────────

	[Test]
	public async Task FragmentContentMatchesOfficialBinary()
	{
		var refFragmentsPath = Path.Combine(ReferenceDecodedDir, "fragments.json");
		if (!File.Exists(refFragmentsPath))
			return;

		var (pagefindDir, cleanup) = await BuildAndWriteIndex();
		try
		{
			var ourFragments = IndexDecoder.ReadAllFragments(Path.Combine(pagefindDir, "fragment"));
			var refJson = await File.ReadAllTextAsync(refFragmentsPath);
			var refFragments = JsonSerializer.Deserialize<List<DecodedFragment>>(refJson,
				DecoderSerializerContext.Default.ListDecodedFragment)!;

			ourFragments.Should().HaveCount(refFragments.Count,
				"should produce the same number of fragments");

			for (var i = 0; i < ourFragments.Count; i++)
			{
				var ours = ourFragments[i];
				var theirs = refFragments[i];

				ours.Url.Should().Be(theirs.Url, $"fragment[{i}] URL mismatch");
				ours.Content.Should().Be(theirs.Content, $"fragment[{i}] content mismatch");
				ours.WordCount.Should().Be(theirs.WordCount, $"fragment[{i}] word count mismatch");

				ours.Meta.Should().BeEquivalentTo(theirs.Meta,
					$"fragment[{i}] ({ours.Url}) meta mismatch");
			}
		}
		finally { cleanup(); }
	}

	// ── Meta Parity ────────────────────────────────────────────────────────────

	[Test]
	public async Task MetaStructureMatchesOfficialBinary()
	{
		var refMetaPath = Path.Combine(ReferenceDecodedDir, "meta.json");
		if (!File.Exists(refMetaPath))
			return;

		var (pagefindDir, cleanup) = await BuildAndWriteIndex();
		try
		{
			var ourMetaFile = IndexDecoder.FindMetaFile(pagefindDir);
			ourMetaFile.Should().NotBeNull("a .pf_meta file should exist");

			var ourMeta = IndexDecoder.ReadMeta(ourMetaFile!);
			var refJson = await File.ReadAllTextAsync(refMetaPath);
			var refMeta = JsonSerializer.Deserialize<DecodedMetaJson>(refJson)!;

			ourMeta.Version.Should().Be(refMeta.Version, "meta version mismatch");

			ourMeta.Pages.Should().HaveCount(refMeta.Pages.Count,
				"should have the same number of pages");

			for (var i = 0; i < ourMeta.Pages.Count; i++)
			{
				ourMeta.Pages[i].WordCount.Should().Be(refMeta.Pages[i].WordCount,
					$"page[{i}] word count mismatch");
			}

			ourMeta.Chunks.Should().HaveCount(refMeta.IndexChunks.Count,
				"should have the same number of index chunks");

			for (var i = 0; i < ourMeta.Chunks.Count; i++)
			{
				ourMeta.Chunks[i].From.Should().Be(refMeta.IndexChunks[i].From,
					$"chunk[{i}] 'from' word mismatch");
				ourMeta.Chunks[i].To.Should().Be(refMeta.IndexChunks[i].To,
					$"chunk[{i}] 'to' word mismatch");
			}

			ourMeta.MetaFields.Should().BeEquivalentTo(refMeta.MetaFields,
				"meta fields should match");
		}
		finally { cleanup(); }
	}

	// ── Entry.json Format Parity ───────────────────────────────────────────────

	[Test]
	public async Task EntryJsonFormatMatchesOfficialBinary()
	{
		var refEntryPath = Path.Combine(ReferenceDecodedDir, "entry.json");
		if (!File.Exists(refEntryPath))
			return;

		var (pagefindDir, cleanup) = await BuildAndWriteIndex();
		try
		{
			var ourEntryJson = await File.ReadAllTextAsync(
				Path.Combine(pagefindDir, "pagefind-entry.json"));
			using var ourDoc = JsonDocument.Parse(ourEntryJson);

			var refEntryJson = await File.ReadAllTextAsync(refEntryPath);
			using var refDoc = JsonDocument.Parse(refEntryJson);

			// Version must match
			ourDoc.RootElement.GetProperty("version").GetString()
				.Should().Be(refDoc.RootElement.GetProperty("version").GetString(),
					"entry.json version mismatch");

			// include_characters must be an array (not a string)
			var ourInclude = ourDoc.RootElement.GetProperty("include_characters");
			ourInclude.ValueKind.Should().Be(JsonValueKind.Array,
				"include_characters should be serialized as a JSON array");

			var refInclude = refDoc.RootElement.GetProperty("include_characters");
			var refChars = refInclude.EnumerateArray()
				.Select(e => e.GetString()!)
				.Order()
				.ToList();

			var ourChars = ourInclude.EnumerateArray()
				.Select(e => e.GetString()!)
				.Order()
				.ToList();

			ourChars.Should().BeEquivalentTo(refChars,
				"include_characters array should contain the same connector chars");

			// Language entry structure
			var ourLangs = ourDoc.RootElement.GetProperty("languages");
			var refLangs = refDoc.RootElement.GetProperty("languages");
			ourLangs.TryGetProperty("en", out _).Should().BeTrue("should have 'en' language entry");

			var ourEn = ourLangs.GetProperty("en");
			var refEn = refLangs.GetProperty("en");
			ourEn.GetProperty("wasm").GetString()
				.Should().Be(refEn.GetProperty("wasm").GetString(), "wasm field mismatch");
			ourEn.GetProperty("page_count").GetInt32()
				.Should().Be(refEn.GetProperty("page_count").GetInt32(), "page_count mismatch");
		}
		finally { cleanup(); }
	}

	// ── Helpers ────────────────────────────────────────────────────────────────

	private static async Task<(string PagefindDir, Action Cleanup)> BuildAndWriteIndex()
	{
		var outputDir = Path.Combine(Path.GetTempPath(), $"pagefind-net-parity-{Guid.NewGuid():N}");
		var index = BuildIndex();
		await index.WriteAsync(outputDir, CancellationToken.None);
		var pagefindDir = Path.Combine(outputDir, "pagefind");
		return (pagefindDir, () =>
		{
			if (Directory.Exists(outputDir))
				Directory.Delete(outputDir, recursive: true);
		});
	}

	/// <summary>
	/// Builds the index using the exact same records that generate-fixtures.mjs
	/// passes to addCustomRecord. All content uses weight 24 (pagefind's body
	/// text weight = 1 * multiplier 24), with real PascalCase content for full
	/// tokenizer parity.
	/// </summary>
	private static PagefindIndex BuildIndex()
	{
		var index = new PagefindIndex(new PagefindIndexOptions { Language = "en" });

		index.AddRecord(new PagefindRecord
		{
			Url = "/getting-started/",
			Title = "Getting Started",
			Content = "Welcome to pagefind-net. Install the NuGet package and call WriteAsync.",
			WeightedSegments =
			[
				new WeightedSegment("Welcome to pagefind-net. Install the NuGet package and call WriteAsync.", Weight: PagefindWeights.Body),
			],
			Meta = new Dictionary<string, string> { ["title"] = "Getting Started" },
		});

		index.AddRecord(new PagefindRecord
		{
			Url = "/configuration/",
			Title = "Configuration",
			Content = "Configure PagefindIndexOptions: Language, IncludeCharacters, WeightedSegments.",
			WeightedSegments =
			[
				new WeightedSegment("Configure PagefindIndexOptions: Language, IncludeCharacters, WeightedSegments.", Weight: PagefindWeights.Body),
			],
			Meta = new Dictionary<string, string> { ["title"] = "Configuration" },
		});

		index.AddRecord(new PagefindRecord
		{
			Url = "/api-reference/",
			Title = "API Reference",
			Content = "PagefindIndex, PagefindRecord, WeightedSegment, PagefindAnchor — full API reference.",
			WeightedSegments =
			[
				new WeightedSegment("PagefindIndex, PagefindRecord, WeightedSegment, PagefindAnchor — full API reference.", Weight: PagefindWeights.Body),
			],
			Meta = new Dictionary<string, string> { ["title"] = "API Reference" },
		});

		return index;
	}
}

// ── JSON DTOs for deserializing reference fixture files ────────────────────────

internal sealed class DecodedMetaJson
{
	[System.Text.Json.Serialization.JsonPropertyName("version")]
	public string Version { get; set; } = "";

	[System.Text.Json.Serialization.JsonPropertyName("pages")]
	public List<DecodedMetaPageJson> Pages { get; set; } = [];

	[System.Text.Json.Serialization.JsonPropertyName("indexChunks")]
	public List<DecodedMetaChunkJson> IndexChunks { get; set; } = [];

	[System.Text.Json.Serialization.JsonPropertyName("metaFields")]
	public List<string> MetaFields { get; set; } = [];
}

internal sealed class DecodedMetaPageJson
{
	[System.Text.Json.Serialization.JsonPropertyName("hash")]
	public string Hash { get; set; } = "";

	[System.Text.Json.Serialization.JsonPropertyName("wordCount")]
	public int WordCount { get; set; }
}

internal sealed class DecodedMetaChunkJson
{
	[System.Text.Json.Serialization.JsonPropertyName("from")]
	public string From { get; set; } = "";

	[System.Text.Json.Serialization.JsonPropertyName("to")]
	public string To { get; set; } = "";

	[System.Text.Json.Serialization.JsonPropertyName("hash")]
	public string Hash { get; set; } = "";
}
