<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Pagefind.Net.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="System.Formats.Cbor" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Pagefind.Net\Pagefind.Net.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Corpus\**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Fixtures\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
